# Generated by Django 5.0.3 on 2024-03-30 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0003_alter_post_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noteuser',
            name='name',
        ),
    ]
