# Generated by Django 5.0.3 on 2024-03-30 14:46

import django.core.files.storage.filesystem
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0004_remove_noteuser_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(storage=django.core.files.storage.filesystem.FileSystemStorage, upload_to='img'),
        ),
    ]
