# Generated by Django 5.0.3 on 2024-03-31 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0007_rename_description_post_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='topic',
            field=models.CharField(max_length=100),
        ),
    ]
