# Generated by Django 5.0.3 on 2024-04-12 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0008_alter_post_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='noteuser',
            name='code',
            field=models.CharField(default=66666, max_length=5),
        ),
    ]
