# Generated by Django 5.0.3 on 2024-04-13 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0010_alter_post_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='topic',
            field=models.CharField(max_length=10),
        ),
    ]
